### PR TITLE
doc generation: put extra sphins options into file...

### PR DESCRIPTION
**Pull request by rgerhards**
this is far less confusing than double-escaping the quotes

requires https://github.com/rsyslog/rsyslog-doc/pull/545

### CODE REVIEW

**Comment by rgerhards** [comment]
@deoren have a look here how we can use the new file-based config addition to avoid uncertainty with double escaping. Still the eval is required inside the container, just as a side note. But usability IMHO is much better.

**Comment by deoren** [comment]
From what I read, there is an option to inject a file directly into a running container. This might be useful in place of copying the file locally, running the container with the bind mount (where the container uses the file) and then removing the file after.

I'm busy with some other stuff otherwise I'd look it up and paste the details here, but I wanted to mention this while I was thinking about it.

Tangent: I lack the permissions with the other projects (including this one) that I have with the source and docs projects. If that's intentional I'm fine with that, but I wanted to mention this just in case you had the intention of level privileges in all projects.

**Comment by rgerhards** [comment]
Sent from phone, thus brief.

Am 06.02.2018 16:10 schrieb "Deoren Moor" <notifications@github.com>:

From what I read, there is an option to inject a file directly into a
running container. This might be useful in place of copying the file
locally, running the container with the bind mount (where the container
uses the file) and then removing the file after.


You got me. The abuilding container actually does that. Let me check...

I'm busy with some other stuff otherwise I'd look it up and paste the
details here, but I wanted to mention this while I was thinking about it.

Tangent: I lack the permissions with the other projects (including this
one) that I have with the source and docs projects. If that's intentional
I'm fine with that, but I wanted to mention this just in case you had the
intention of level privileges in all projects.


I overlooked that. Be on the road right now, will check later.

**Comment by deoren** [comment]
> deoren: From what I read, there is an option to inject a file directly into a running container. This might be useful in place of copying the file locally, running the container with the bind mount (where the container uses the file) and then removing the file after.

Here it is:

https://docs.docker.com/engine/reference/commandline/cp/

> **Description**
> 
> Copy files/folders between a container and the local filesystem
> 
> **Usage**
> 
> - `docker cp [OPTIONS] CONTAINER:SRC_PATH DEST_PATH|-`
> - `docker cp [OPTIONS] SRC_PATH|- CONTAINER:DEST_PATH`

**Comment by deoren** [comment]
> @deoren: From what I read, there is an option to inject a file directly into a running container. 

That said, unless you fork the container into the background when you run it, your build script would have a hard time copying a file into it. It may be that the process you're using is the better approach.

**Comment by deoren** [comment]
> @rgerhards: @deoren have a look here how we can use the new file-based config addition to avoid uncertainty with double escaping. Still the eval is required inside the container, just as a side note. But usability IMHO is much better.

That's a pretty neat trick. I'm not sure if I've used that approach before, but I'll be sure to remember it.

**Comment by rgerhards** [comment]
> That said, unless you fork the container into the background when you run it, your build script would have a hard time copying a file into it. It may be that the process you're using is the better approach.

I think you can actually **map** (mount) the file into the container. Not just on dir level. Let's see if I can come up quick (with the help of the abuild container).

**Comment by rgerhards** [comment]
yup:
```
-v "$WEB_PRJ_HOME/tools/gendoc/SPHINX_EXTRA_OPTS:/rsyslog-doc/SPHINX_EXTRA_OPTS"
```
updated PR accordingly.

**Pull request merged**
